-- ============================================================
-- FEZA SMART MOCK DATA - Essential Test Data
-- ============================================================
-- Using correct snake_case column names as generated by Hibernate

-- Password hash: Feza@2024 (BCrypt $2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG)

-- ============================================================
-- Users (Super Admin & Directors)
-- ============================================================
INSERT INTO user (username, hashed_password, email, phone, is_active, email_verified, phone_verified, two_factor_enabled, created_at, updated_at) VALUES
('admin_super', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'admin@fezasmart.com', '+254712345678', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('director_main', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'director@fezasmart.com', '+254712345679', TRUE, TRUE, FALSE, FALSE, NOW(), NOW());

-- ============================================================
-- Academic Years
-- ============================================================
INSERT INTO academic_year (name, start_date, end_date, created_at) VALUES
('2024', '2024-01-15', '2024-11-30', NOW()),
('2025', '2025-01-20', '2025-11-30', NOW());

-- ============================================================
-- Terms
-- ============================================================
INSERT INTO term (academic_year_id, name, start_date, end_date, created_at) VALUES
(1, 'Term 1', '2024-01-15', '2024-04-12', NOW()),
(1, 'Term 2', '2024-05-06', '2024-08-09', NOW()),
(1, 'Term 3', '2024-08-19', '2024-11-15', NOW()),
(2, 'Term 1', '2025-01-20', '2025-04-18', NOW());

-- ============================================================
-- Schools
-- ============================================================
INSERT INTO school (name, email, phone, city, country, is_active, created_at, updated_at) VALUES
('Kampala Senior School', 'info@kss.ug', '+256414123456', 'Kampala', 'Uganda', TRUE, NOW(), NOW()),
('St. Mary\'s Secondary', 'admin@stmarys.ug', '+256414789012', 'Kampala', 'Uganda', TRUE, NOW(), NOW()),
('Muyenga High School', 'contact@muyenga.ug', '+256414345678', 'Kampala', 'Uganda', TRUE, NOW(), NOW());

-- ============================================================
-- Staff Users (School 1: Kampala Senior School)
-- ============================================================
INSERT INTO user (username, hashed_password, email, phone, is_active, email_verified, phone_verified, two_factor_enabled, created_at, updated_at) VALUES
('headmaster_kss', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'headmaster@kss.ug', '+256712111111', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('deputy_kss', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'deputy@kss.ug', '+256712111112', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('hr_kss', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'hr@kss.ug', '+256712111113', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('teacher_math_kss', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'mwangi@kss.ug', '+256712111114', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('teacher_english_kss', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'jane@kss.ug', '+256712111115', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('teacher_science_kss', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'john@kss.ug', '+256712111116', TRUE, TRUE, FALSE, FALSE, NOW(), NOW());

-- ============================================================
-- Staff Records
-- ============================================================
INSERT INTO staff (user_id, school_id, first_name, last_name, join_date, is_active) VALUES
(3, 1, 'David', 'Kipchoge', '2019-01-10', TRUE),
(4, 1, 'Margaret', 'Omondi', '2020-03-15', TRUE),
(5, 1, 'Robert', 'Njeri', '2021-02-20', TRUE),
(6, 1, 'Mwangi', 'Kariuki', '2021-09-01', TRUE),
(7, 1, 'Jane', 'Muthoni', '2022-01-15', TRUE),
(8, 1, 'John', 'Kosgey', '2021-06-10', TRUE);

-- ============================================================
-- Classes
-- ============================================================
INSERT INTO classs (name, school_id, academic_year_id, created_at) VALUES
('Form 1A', 1, 1, NOW()),
('Form 1B', 1, 1, NOW()),
('Form 2A', 1, 1, NOW()),
('Form 3A', 1, 1, NOW()),
('Form 4A', 1, 1, NOW());

-- ============================================================
-- Subjects
-- ============================================================
INSERT INTO subject (name, type, created_at) VALUES
('Mathematics', 'CORE', NOW()),
('English Language', 'CORE', NOW()),
('Biology', 'SCIENCE', NOW()),
('Chemistry', 'SCIENCE', NOW()),
('Physics', 'SCIENCE', NOW()),
('Geography', 'SOCIAL', NOW()),
('History', 'SOCIAL', NOW()),
('Kiswahili', 'LANGUAGE', NOW());

-- ============================================================
-- Parent Users
-- ============================================================
INSERT INTO user (username, hashed_password, email, phone, is_active, email_verified, phone_verified, two_factor_enabled, created_at, updated_at) VALUES
('parent_kimani', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'parent1@email.com', '+256789111111', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('parent_nairobi', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'parent2@email.com', '+256789111112', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('parent_mombasa', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'parent3@email.com', '+256789111113', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('parent_nakuru', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'parent4@email.com', '+256789111114', TRUE, TRUE, FALSE, FALSE, NOW(), NOW());

-- ============================================================
-- Parents
-- ============================================================
INSERT INTO parent (user_id, school_id, first_name, last_name, phone, email, is_active) VALUES
(9, 1, 'Samuel', 'Kimani', '+256789111111', 'parent1@email.com', TRUE),
(10, 1, 'Anne', 'Nairobi', '+256789111112', 'parent2@email.com', TRUE),
(11, 1, 'Peter', 'Mombasa', '+256789111113', 'parent3@email.com', TRUE),
(12, 1, 'Grace', 'Nakuru', '+256789111114', 'parent4@email.com', TRUE);

-- ============================================================
-- Student Users
-- ============================================================
INSERT INTO user (username, hashed_password, email, phone, is_active, email_verified, phone_verified, two_factor_enabled, created_at, updated_at) VALUES
('student_001', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'student1@kss.ug', '+256701001001', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('student_002', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'student2@kss.ug', '+256701001002', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('student_003', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'student3@kss.ug', '+256701001003', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('student_004', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'student4@kss.ug', '+256701001004', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('student_005', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'student5@kss.ug', '+256701001005', TRUE, TRUE, FALSE, FALSE, NOW(), NOW()),
('student_006', '$2a$10$slYQmyNdGzin7olVCeOU2OPST9/PgBkqquzi.Ye5SYXAZZbqPgDlG', 'student6@kss.ug', '+256701001006', TRUE, TRUE, FALSE, FALSE, NOW(), NOW());

-- ============================================================
-- Students
-- ============================================================
INSERT INTO student (user_id, school_id, first_name, last_name, date_of_birth, guardian_name, guardian_phone, is_active, admission_date, created_at) VALUES
(13, 1, 'David', 'Kipchoge', '2008-05-15', 'Samuel Kimani', '+256789111111', TRUE, '2022-01-20', NOW()),
(14, 1, 'Sarah', 'Omondi', '2008-07-22', 'Anne Nairobi', '+256789111112', TRUE, '2022-01-20', NOW()),
(15, 1, 'Michael', 'Kosgey', '2008-09-10', 'Peter Mombasa', '+256789111113', TRUE, '2022-01-20', NOW()),
(16, 1, 'Grace', 'Muthoni', '2008-11-03', 'Grace Nakuru', '+256789111114', TRUE, '2022-01-20', NOW()),
(17, 1, 'Joseph', 'Kimani', '2008-03-28', 'Samuel Kimani', '+256789111111', TRUE, '2022-01-20', NOW()),
(18, 1, 'Linda', 'Kipkemoi', '2008-06-14', 'Anne Nairobi', '+256789111112', TRUE, '2022-01-20', NOW());

-- ============================================================
-- Student Enrollments
-- ============================================================
INSERT INTO student_enrollment (student_id, classs_id, academic_year_id, enrollment_date, is_active) VALUES
(1, 1, 1, '2024-01-15', TRUE),
(2, 1, 1, '2024-01-15', TRUE),
(3, 1, 1, '2024-01-15', TRUE),
(4, 2, 1, '2024-01-15', TRUE),
(5, 2, 1, '2024-01-15', TRUE),
(6, 2, 1, '2024-01-15', TRUE);

-- ============================================================
-- Exams
-- ============================================================
INSERT INTO exam (name, term_id, exam_date, created_at) VALUES
('Midterm Test 1', 1, '2024-02-20', NOW()),
('End of Term 1 Exam', 1, '2024-04-05', NOW()),
('Midterm Test 2', 2, '2024-06-15', NOW()),
('End of Term 2 Exam', 2, '2024-07-30', NOW());

-- ============================================================
-- Exam Subjects
-- ============================================================
INSERT INTO exam_subject (exam_id, subject_id) VALUES
(1, 1), (1, 2), (1, 3), (1, 4),
(2, 1), (2, 2), (2, 3), (2, 4), (2, 5),
(3, 1), (3, 2), (3, 3), (3, 4),
(4, 1), (4, 2), (4, 3), (4, 4), (4, 5);

-- ============================================================
-- Student Scores (Term 1 Midterm)
-- ============================================================
INSERT INTO student_score (student_id, exam_subject_id, score) VALUES
(1, 1, 85.5), (1, 2, 78.0), (1, 3, 92.0), (1, 4, 88.5),
(2, 1, 92.0), (2, 2, 85.5), (2, 3, 88.0), (2, 4, 91.0),
(3, 1, 78.0), (3, 2, 82.0), (3, 3, 75.5), (3, 4, 80.0),
(4, 1, 88.0), (4, 2, 90.5), (4, 3, 85.0), (4, 4, 87.5),
(5, 1, 75.0), (5, 2, 80.0), (5, 3, 82.5), (5, 4, 78.0),
(6, 1, 95.0), (6, 2, 93.5), (6, 3, 91.0), (6, 4, 94.5);

-- ============================================================
-- Results (Aggregated)
-- ============================================================
INSERT INTO result (student_id, exam_id, total_score, average_percentage, total_points, division, rank_in_class, remark, computed_at) VALUES
(1, 1, 343.5, 85.9, 86, 'A', 2, 'Excellent', NOW()),
(2, 1, 356.5, 89.1, 89, 'A', 1, 'Excellent', NOW()),
(3, 1, 315.5, 78.9, 79, 'B', 4, 'Good', NOW()),
(4, 1, 350.5, 87.6, 88, 'A', 3, 'Excellent', NOW()),
(5, 1, 315.5, 78.9, 79, 'B', 5, 'Good', NOW()),
(6, 1, 373.5, 93.4, 93, 'A', 1, 'Excellent', NOW());

-- ============================================================
-- Roles
-- ============================================================
INSERT INTO role (name, description) VALUES
('SUPER_ADMIN', 'System administrator with full access'),
('HEAD_MASTER', 'School head with full school control'),
('GENERAL_SECOND_MASTER', 'Sees everything in the school'),
('HUMAN_RESOURCE', 'Controls staff and attendance'),
('SECOND_MASTER', 'Controls specific classes'),
('PARENT', 'Views student results and school info'),
('STUDENT', 'Views own results');

-- ============================================================
-- Permissions
-- ============================================================
INSERT INTO permission (name, description) VALUES
('CREATE_USER', 'Create new users'),
('READ_USER', 'View user information'),
('UPDATE_USER', 'Update user details'),
('DELETE_USER', 'Delete users'),
('CREATE_SCHOOL', 'Create new schools'),
('READ_SCHOOL', 'View school information'),
('UPDATE_SCHOOL', 'Update school details'),
('DELETE_SCHOOL', 'Delete schools'),
('CREATE_STUDENT', 'Create new students'),
('READ_STUDENT', 'View student information'),
('UPDATE_STUDENT', 'Update student details'),
('DELETE_STUDENT', 'Delete students'),
('CREATE_STAFF', 'Create staff members'),
('READ_STAFF', 'View staff information'),
('UPDATE_STAFF', 'Update staff details'),
('DELETE_STAFF', 'Delete staff members'),
('CREATE_RESULT', 'Create exam results'),
('READ_RESULT', 'View exam results'),
('UPDATE_RESULT', 'Update results'),
('DELETE_RESULT', 'Delete results'),
('MANAGE_ATTENDANCE', 'Manage staff/student attendance'),
('VIEW_ANALYTICS', 'View performance analytics'),
('EXPORT_REPORT', 'Export reports');

-- ============================================================
-- User Roles
-- ============================================================
INSERT INTO user_role (user_id, role_id) VALUES
(1, 1),   -- admin_super -> SUPER_ADMIN
(3, 2),   -- headmaster_kss -> HEAD_MASTER
(4, 3),   -- deputy_kss -> GENERAL_SECOND_MASTER
(5, 4),   -- hr_kss -> HUMAN_RESOURCE
(6, 5), (7, 5), (8, 5), -- teachers -> SECOND_MASTER
(9, 6), (10, 6), (11, 6), (12, 6), -- parents -> PARENT
(13, 7), (14, 7), (15, 7), (16, 7), (17, 7), (18, 7); -- students -> STUDENT

-- ============================================================
-- Attendance Records
-- ============================================================
INSERT INTO attendance_record (staff_id, attendance_date, is_present, check_in_time, check_out_time, remarks, created_at) VALUES
(1, '2024-02-20', TRUE, '08:00:00', '16:30:00', 'Regular', NOW()),
(1, '2024-02-21', TRUE, '08:05:00', '16:30:00', 'Regular', NOW()),
(2, '2024-02-20', TRUE, '08:00:00', '16:30:00', 'Regular', NOW()),
(2, '2024-02-21', FALSE, NULL, NULL, 'Sick leave', NOW()),
(3, '2024-02-20', TRUE, '08:00:00', '16:30:00', 'Regular', NOW()),
(3, '2024-02-21', TRUE, '08:10:00', '16:30:00', 'Regular', NOW());

-- ============================================================
-- API Keys
-- ============================================================
INSERT INTO api_key (key, name, description, is_active, created_at, expires_at) VALUES
('feza_api_key_2024_001', 'Mobile App API Key', 'API key for React Native mobile application', TRUE, NOW(), DATE_ADD(NOW(), INTERVAL 1 YEAR)),
('feza_api_key_2024_002', 'Web Portal API Key', 'API key for web administration portal', TRUE, NOW(), DATE_ADD(NOW(), INTERVAL 1 YEAR));

-- ============================================================
-- SUMMARY
-- ============================================================
-- Total Records Inserted:
-- Users: 18 (2 admins + 6 staff + 4 parents + 6 students)
-- Schools: 3
-- Staff: 6
-- Academic Years: 2
-- Terms: 4
-- Classes: 5
-- Subjects: 8
-- Students: 6
-- Exams: 4
-- Exam Subjects: 18
-- Student Scores: 24
-- Results: 6
-- Roles: 7
-- Permissions: 23
-- Parents: 4
-- Enrollments: 6
-- Attendance Records: 6
-- API Keys: 2
